### PR TITLE
Embed manifest resource using MSVC toolchain, to avoid installer heuristics.

### LINKED ISSUE #11: 'unknown error occurred': It implicitly requires to be run as Administrator on Windows
```
C:\Users\liigo>cargo install-update
error: An unknown error occurred

To learn more, run the command again with --verbose.

C:\Users\liigo>cargo install-update --verbose
error: An unknown error occurred

To learn more, run the command again with --verbose.
```

If run it as administrator, it works.

----

Update: to know the reason and workaround, see comments after [this](https://github.com/nabijaczleweli/cargo-update/issues/11#issuecomment-260555826)

### LINKED ISSUE #14: MSVC does actually require an explicit manifest, currently ignored
```
cannot open input file 'cargo-install-update-manifest.lib'
```

that .lib was not created by build.rs

### PR DESCRIPTION
**Pull request by liigo**
I tested it on Windows 10 + MSVC 2015. The manifest resource was linked into .exe, which don't requires administrator privilege to be run anymore. (I didn't touch existing code for gnu toolchain, it will continue works, if it did works.)

See comments on #11 for more information.
Fixes #11
Fixes #14

@nabijaczleweli r?

### CODE REVIEW

File: build.rs [hunk 1]
```diff
@@ -17,7 +21,20 @@ fn main() {
             .current_dir(&Path::new(&out_dir))
             .status()
             .unwrap();
+    }
+
+    if cfg!(target_env = "msvc") {
+        // We'll create a `.res` file here, but name it as `.lib`,
+        // so that it can be found and linked correctly.
+        // Yes, `.res` may be linked directly, like `.lib` and `.o`.
```
Comment (liigo) [inline build.rs]: I don't know why, but I know it works:)

**Comment by nabijaczleweli** [comment]
Works on GNU too, nice work

File: build.rs (hunk 1 above)
Comment (nabijaczleweli) [inline build.rs]: `msvc.txt`

**Comment by mzji** [comment]
By [the document](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648007(v=vs.85).aspx), the msvc linker will recognize the resource bijary file, convert it to a COFF object file and link it to the final binary.

**Comment by nabijaczleweli** [comment]
Another case of counter-intuitive specialcasing by M$, :goodjob:

**Comment by mzji** [comment]
Well, on Windows, it is a common practice that include the compiled resources inside the final PE binary, so I think what MSVC's link.exe did here makes sense. Yeah, it's a bit anti-intuitive for Unix people since the PE file could include icons (which is binary resource, IMO), but the ELF/Mach-O can't. 

Reference: [Comparison of executable file formats on Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_executable_file_formats), note the "Icon" part.

**Comment by liigo** [comment]
An useful feature, not counter-intuitive, IMHO.

**Comment by nabijaczleweli** [comment]
Useful: yes, counter-intuitive: slightly, since you get an object file you can link to/
